const data = [
    {
        id: "1",
        name: "Trưởng nhóm thiết kế",
        link: "recruitDesign.html",
        deadline: "01/09/2022",
        department: "design",
        location: "Hồ Chí Minh",
    },
    {
        id: "2",
        name: "Trưởng nhóm Truyền thông quảng cáo",
        link: "#",
        deadline: "01/09/2022",
        department: "advertisement",
        location: "Hà Nội",
    },
    {
        id: "3",
        name: "Trưởng nhóm quản trị dịch vụ",
        link: "#",
        department: "service",
        deadline: "01/09/2022",
        location: "Hà Nội",
    },
    {
        id: "4",
        name: "Chuyên viên thiết kế đồ họa",
        link: "#",
        department: "design",
        deadline: "01/09/2022",
        location: "Hồ Chí Minh",
    },
    {
        id: "5",
        name: "Trưởng nhóm IT",
        link: "#",
        department: "it",
        deadline: "01/09/2022",
        location: "Hà Nội",
    },
    {
        id: "6",
        name: "nhân viên IT",
        link: "#",
        department: "it",
        deadline: "01/09/2022",
        location: "Hồ Chí Minh",
    },
    {
        id: "7",
        name: "Trưởng nhóm thiết kế",
        link: "#",
        deadline: "01/09/2022",
        department: "design",
        location: "Hà Nội",
    },
];

